import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "./redux/providers/ReduxProvider";
import BottomNavigation from "./components/bottom-navigation";
import QueryClientProviderWrapper from "./redux/providers/QueryClientProvider";
import { Toaster } from "sonner";

const geistSans = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Roboto_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <Toaster />
        <QueryClientProviderWrapper>
          <ReduxProvider>
            <main className=" mx-auto">{children}</main>
            {/* <CartDetailsBar /> */}
            <BottomNavigation />
          </ReduxProvider>
        </QueryClientProviderWrapper>
      </body>
    </html>
  );
}
